site_name: ANNOVAR Documentation
site_url: http://annovar.openbioinformatics.org/
repo_url: http://github.com/WGLab/doc-ANNOVAR/
repo_name: GitHub
site_description: Documentation for ANNOVAR software
site_author: Kai Wang, et al
site_favicon: favicon.ico
copyright: 2010-2016 ANNOVAR
google_analytics: ['UA-48623707-1', 'annovar.openbioinformatics.org']

docs_dir: .
include_search: true
#use_absolute_urls: true
#use_directory_urls: false

pages:
- ANNOVAR: index.md
- User Guide:
  - Download ANNOVAR: user-guide/download.md
  - Quick Start-Up Guide: user-guide/startup.md
  - Prepare Input Files: user-guide/input.md
  - Gene-based Annotation: user-guide/gene.md
  - Region-based Annotation: user-guide/region.md
  - Filter-based Annotation: user-guide/filter.md
- Misc:
  - Accessory Programs: misc/accessory.md
  - FAQ: misc/faq.md
  - What is New: misc/whatsnew.md
  - Version History: misc/version_history.md
  - Credit: misc/credit.md
  - How to Contribute: misc/contributing.md
- Articles:
  - VCF Processing Guide: articles/VCF.md
  - Assigning dbSNP Identifiers: articles/dbSNP.md
  - wANNOVAR Tutorial: articles/wANNOVAR.md
